// Generated by scripts/generate_ui_event_types.py. Do not edit by hand.
// Source: sdk/events/_models.py (AgentEventPayload).

export interface ConversationEventMetadata {
    id: string;
    timestamp: string;
    conversation_id: string | null;
    agent_id: string | null;
    agent_name: string | null;
    depth: number;
}

export interface StreamEnvelopeMetadata {
    id?: string | null;
    timestamp?: string | null;
    conversation_id?: string | null;
    agent_id?: string | null;
    agent_name?: string | null;
    depth?: number | null;
}

export interface CompactionScope {
    user_messages: number;
    iterations: number;
    tool_results: number;
}

export interface CompactionStats {
    context_before: number | null;
    context_after: number | null;
    context_limit: number | null;
    saved_tokens: number | null;
    saved_ratio: number | null;
    spanned_seconds: number | null;
    scope: CompactionScope;
    summary_chars: number;
    summary_tokens: number;
    summary_lines: number;
    model: string | null;
    input_char_count: number | null;
    elapsed_seconds: number | null;
}

export interface IterationToolCall {
    id: string | null;
    name: string;
    arguments: Record<string, unknown> | null;
}

export interface UserAttachment {
    filename: string;
    content_type: string;
    path: string;
}

export interface ContentPayload {
    type: 'content';
    content: string | null;
    thinking: string | null;
    delta: boolean | null;
}

export interface TurnEndPayload {
    type: 'turn_end';
}

export interface ToolCallPayload {
    type: 'tool_call';
    name: string;
    arguments: Record<string, string> | null;
}

export interface BrowserScreenshotPayload {
    type: 'browser_screenshot';
    url: string;
    title: string;
    screenshot: string | null;
    tab_id: number | null;
    open_tab_ids: Array<number> | null;
}

export interface FileOutputPayload {
    type: 'file_output';
    filename: string;
    content_type: string;
    content: string | null;
    path: string | null;
    tool_call_id: string | null;
}

export interface ToolCreatedPayload {
    type: 'tool_created';
    name: string;
}

export interface AudioPlaybackPayload {
    type: 'audio_playback';
    content_type: string;
    content: string;
}

export interface TerminalOutputPayload {
    type: 'terminal_output';
    cmd_id: string;
    cmd: string;
    status: 'running' | 'streaming' | 'completed';
    stdout: string | null;
    stderr: string | null;
    exit_code: number | null;
}

export interface GenerationPreviewPayload {
    type: 'generation_preview';
    gen_id: string;
    media_type: string;
    status: 'loading' | 'generating' | 'complete' | 'failed';
    step: number | null;
    total_steps: number | null;
    preview: string | null;
    message: string | null;
    output: string | null;
    output_content_type: string | null;
    output_path: string | null;
}

export interface ContextUsagePayload {
    type: 'context_usage';
    context_used: number;
    context_limit: number;
    fill_ratio: number;
    compaction_threshold: number;
    iteration: number | null;
    max_iterations: number | null;
}

export interface DesktopActivePayload {
    type: 'desktop_active';
    resolution: string;
}

export interface AgentStartedPayload {
    type: 'agent_started';
    agent_id: string;
    agent_name: string;
    parent_agent_id: string | null;
    instruction: string | null;
    profile_name: string | null;
    correlation_id: string | null;
}

export interface AgentCompletedPayload {
    type: 'agent_completed';
    agent_id: string;
    agent_name: string;
    status: 'success' | 'error' | 'stopped';
}

export interface SpawnRequestedPayload {
    type: 'spawn_requested';
    correlation_id: string;
}

export interface UserMessagePayload {
    type: 'user_message';
    content: string;
    attachments: Array<UserAttachment>;
    is_nudge: boolean;
}

export interface IterationPayload {
    type: 'iteration';
    iteration_index: number;
    thinking: string | null;
    content: string | null;
    tool_calls: Array<IterationToolCall>;
    stopped: boolean;
    total_tokens: number | null;
}

export interface ToolResultPayload {
    type: 'tool_result';
    tool_call_id: string | null;
    tool_name: string;
    content: string;
}

export interface CompactionPayload {
    type: 'compaction';
    kept_from_id: string;
    kept_to_id: string;
    summary_text: string;
    user_intent_summary: string | null;
    stats: CompactionStats | null;
}

export interface ErrorPayload {
    type: 'error';
    message: string;
    retryable: boolean;
}

export type ConversationEventPayload =
    | ContentPayload
    | TurnEndPayload
    | ToolCallPayload
    | BrowserScreenshotPayload
    | FileOutputPayload
    | ToolCreatedPayload
    | AudioPlaybackPayload
    | TerminalOutputPayload
    | GenerationPreviewPayload
    | ContextUsagePayload
    | DesktopActivePayload
    | AgentStartedPayload
    | AgentCompletedPayload
    | SpawnRequestedPayload
    | UserMessagePayload
    | IterationPayload
    | ToolResultPayload
    | CompactionPayload
    | ErrorPayload;

export type ConversationEvent =
    | (ConversationEventMetadata & ContentPayload)
    | (ConversationEventMetadata & TurnEndPayload)
    | (ConversationEventMetadata & ToolCallPayload)
    | (ConversationEventMetadata & BrowserScreenshotPayload)
    | (ConversationEventMetadata & FileOutputPayload)
    | (ConversationEventMetadata & ToolCreatedPayload)
    | (ConversationEventMetadata & AudioPlaybackPayload)
    | (ConversationEventMetadata & TerminalOutputPayload)
    | (ConversationEventMetadata & GenerationPreviewPayload)
    | (ConversationEventMetadata & ContextUsagePayload)
    | (ConversationEventMetadata & DesktopActivePayload)
    | (ConversationEventMetadata & AgentStartedPayload)
    | (ConversationEventMetadata & AgentCompletedPayload)
    | (ConversationEventMetadata & SpawnRequestedPayload)
    | (ConversationEventMetadata & UserMessagePayload)
    | (ConversationEventMetadata & IterationPayload)
    | (ConversationEventMetadata & ToolResultPayload)
    | (ConversationEventMetadata & CompactionPayload)
    | (ConversationEventMetadata & ErrorPayload);

export type StreamEnvelope = StreamEnvelopeMetadata & {
    payload?: ConversationEventPayload | null;
};
