"""Live and resumed turns generated by real nudge, compaction, and spawn paths."""

import time

from playwright.sync_api import Page, expect

from tests.e2e._protocol import model_script, model_tool, say, spawn
from tests.e2e._runtime import (
    agent_profile, api, compaction_script, compaction_settings, delete_conversation,
    resume, run_turn, update_conversation,
)
from tests.e2e.pages import ChatView, RecentConversations


def _select_profile(page, profile):
    page.get_by_label("Agent profile").click()
    page.get_by_role("option", name=profile["name"], exact=True).click()


def _nudge_turn(page):
    captured = {}
    page.on("request", lambda request: captured.update(request.post_data_json)
            if request.method == "POST" and request.url.endswith("/api/chat") else None)
    chat = ChatView(page).goto().new_conversation()
    chat.send("run a long task " + model_script(
        {"content": "starting on it", "tool_calls": [model_tool("run_bash_cmd", cmd="sleep 3")]},
        {"content": "obsolete answer"},
    ))
    expect(page.get_by_test_id("entry-content").last).to_contain_text("starting on it", timeout=10_000)
    conversation = captured["conversation_id"]
    snapshot = resume(conversation)
    root = next(e for e in snapshot["events"] if e["type"] == "agent_started" and not e.get("parent_agent_id"))
    response = api().post("/api/nudge", data={
        "conversation_id": conversation, "agent_id": root["agent_id"],
        "message": "also do step two " + say("step two done"),
    })
    assert response.status == 200
    chat.wait_streaming(timeout=10_000)
    return conversation


def _assert_nudge_order(page):
    expect(page.get_by_test_id("turn")).to_have_count(1)
    expect(page.get_by_test_id("message-user")).to_have_count(2)
    expect(page.get_by_test_id("message-assistant")).to_have_count(2)
    expect(page.get_by_test_id("message-user").nth(0)).to_contain_text("run a long task")
    expect(page.get_by_test_id("message-user").nth(1)).to_contain_text("also do step two")
    expect(page.get_by_test_id("message-assistant").nth(0)).to_contain_text("starting on it")
    expect(page.get_by_test_id("message-assistant").nth(1)).to_contain_text("step two done")
    rows = page.locator("[data-testid='message-user'], [data-testid='message-assistant']")
    assert rows.evaluate_all("els => els.map(el => el.dataset.testid)") == [
        "message-user", "message-assistant", "message-user", "message-assistant",
    ]


def test_live_nudge_renders_as_inline_user_message(page: Page):
    conversation = _nudge_turn(page)
    try:
        _assert_nudge_order(page)
    finally:
        delete_conversation(conversation)


def test_resume_nudge_renders_inline(page: Page):
    conversation = _nudge_turn(page)
    try:
        ChatView(page).goto().new_conversation()
        RecentConversations(page).open_by_id(conversation)
        _assert_nudge_order(page)
    finally:
        delete_conversation(conversation)


def _assert_compaction_order(page):
    expect(page.get_by_test_id("turn")).to_have_count(1)
    expect(page.get_by_test_id("compaction-chip")).to_have_count(1)
    expect(page.get_by_test_id("message-assistant")).to_have_count(2)
    expect(page.get_by_test_id("message-assistant").nth(0)).to_contain_text("pre-compaction work 0")
    expect(page.get_by_test_id("message-assistant").nth(1)).to_contain_text("post-compaction work")
    boxes = page.locator("[data-testid='message-assistant'], [data-testid='compaction-row']")
    assert boxes.evaluate_all("els => els.map(el => el.dataset.testid)") == [
        "message-assistant", "compaction-row", "message-assistant",
    ]


def test_live_compaction_chip_splits_assistant_mid_turn(page: Page):
    captured = {}
    page.on("request", lambda request: captured.update(request.post_data_json)
            if request.method == "POST" and request.url.endswith("/api/chat") else None)
    with compaction_settings(), agent_profile(context_window=1000, compaction_threshold=0.01) as profile:
        chat = ChatView(page).goto().new_conversation()
        _select_profile(page, profile)
        try:
            chat.send(compaction_script()).wait_streaming()
            _assert_compaction_order(page)
            assert len([e for e in resume(captured["conversation_id"])["events"] if e["type"] == "compaction"]) == 1
        finally:
            if captured:
                delete_conversation(captured["conversation_id"])


def test_resume_mid_turn_compaction_splits_assistant(page: Page):
    conversation = f"e2e_compaction_resume_{time.time_ns()}"
    with compaction_settings(), agent_profile(context_window=1000, compaction_threshold=0.01) as profile:
        try:
            events = run_turn(conversation, compaction_script(), profile_id=profile["id"])
            assert len([e for e in events if e["payload"]["type"] == "compaction"]) == 1
            ChatView(page).goto().new_conversation()
            RecentConversations(page).open_by_id(conversation)
            _assert_compaction_order(page)
        finally:
            delete_conversation(conversation)


def test_resume_sub_agent_renders_spawn_card_and_network(page: Page):
    conversation = f"e2e_spawn_resume_{time.time_ns()}"
    try:
        run_turn(conversation, "delegate this " + spawn(
            "Compute 7*6 and report " + say("42"), name="ALPHA",
        ) + say("the answer is 42"))
        ChatView(page).goto().new_conversation()
        RecentConversations(page).open_by_id(conversation)
        expect(page.get_by_test_id("turn")).to_have_count(1)
        expect(page.get_by_test_id("message-user")).to_have_count(1)
        expect(page.get_by_test_id("message-user")).to_contain_text("delegate this")
        expect(page.get_by_test_id("spawn-card")).to_be_visible()
        expect(page.get_by_test_id("spawn-card")).to_contain_text("ALPHA")
        expect(page.get_by_test_id("network-indicator")).to_contain_text("2 agents")
        page.get_by_test_id("spawn-card-row").first.click()
        expect(page.get_by_test_id("agent-activity-title")).to_contain_text("ALPHA")
        expect(page.get_by_test_id("instruction-toggle")).to_contain_text("Compute 7*6 and report")
    finally:
        delete_conversation(conversation)
