#!/usr/bin/env python3
"""Generate the frontend conversation-event union from the agent core models."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path
from typing import Annotated, Any, Literal, Union, cast, get_args, get_origin

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUTPUT = ROOT / "server/ui/src/features/conversation/events/conversationEvents.generated.ts"


def _typescript_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is Annotated:
        return _typescript_type(args[0])
    if origin in (Union, types.UnionType):
        return " | ".join(_typescript_type(arg) for arg in args)
    if origin is Literal:
        return " | ".join(repr(value) for value in args)
    if origin is list:
        return f"Array<{_typescript_type(args[0])}>"
    if origin is dict:
        value_type = _typescript_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<string, {value_type}>"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is list:
        return "Array<unknown>"
    if annotation is dict:
        return "Record<string, unknown>"
    if annotation is type(None):
        return "null"
    if annotation is Any:
        return "unknown"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    raise TypeError(f"Unsupported event annotation: {annotation!r}")


def _payload_models() -> list[type[BaseModel]]:
    from agent_core.events._models import AgentEventPayload

    union = get_args(AgentEventPayload)[0]
    return list(get_args(union))


def _nested_models(payload_models: list[type[BaseModel]]) -> list[type[BaseModel]]:
    found: dict[str, type[BaseModel]] = {}

    def visit(annotation: Any) -> None:
        origin = get_origin(annotation)
        args = get_args(annotation)
        if origin is Annotated:
            visit(args[0])
            return
        if origin in (Union, types.UnionType, list, dict):
            for arg in args:
                visit(arg)
            return
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            model = cast(type[BaseModel], annotation)
            if model in payload_models or model.__name__ in found:
                return
            found[model.__name__] = model
            for field in model.model_fields.values():
                visit(field.annotation)

    for model in payload_models:
        for field in model.model_fields.values():
            visit(field.annotation)
    return [found[name] for name in sorted(found)]


def _interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        # AgentEvent.to_flat_dict serializes Pydantic defaults, so the current
        # wire record contains every payload field even when callers omitted a
        # defaulted value while constructing the model.
        lines.append(f"    {name}: {_typescript_type(field.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    """Return the TypeScript source derived from the current agent core models."""
    payload_models = _payload_models()
    nested_models = _nested_models(payload_models)
    lines = [
        "// Generated by scripts/generate_ui_event_types.py. Do not edit by hand.",
        "// Source: agent_core/events/_models.py (AgentEventPayload).",
        "",
        "export interface ConversationEventMetadata {",
        "    id: string;",
        "    timestamp: string;",
        "    conversation_id: string | null;",
        "    agent_id: string | null;",
        "    agent_name: string | null;",
        "    depth: number;",
        "}",
        "",
        "export interface StreamEnvelopeMetadata {",
        "    id?: string | null;",
        "    timestamp?: string | null;",
        "    conversation_id?: string | null;",
        "    agent_id?: string | null;",
        "    agent_name?: string | null;",
        "    depth?: number | null;",
        "}",
        "",
    ]

    for model in [*nested_models, *payload_models]:
        lines.extend([_interface(model), ""])

    payload_names = "\n    | ".join(model.__name__ for model in payload_models)
    event_names = "\n    | ".join(
        f"(ConversationEventMetadata & {model.__name__})" for model in payload_models
    )
    lines.extend([
        "export type ConversationEventPayload =",
        f"    | {payload_names};",
        "",
        "export type ConversationEvent =",
        f"    | {event_names};",
        "",
        "export type StreamEnvelope = StreamEnvelopeMetadata & {",
        "    payload?: ConversationEventPayload | null;",
        "};",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    """Write the generated file, or verify it when passed ``--check``."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
